import test from 'node:test'
import assert from 'node:assert/strict'
if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST)throw new Error('Integration tests require both emulators.')
const {platformAction}=await import('../index.js')
const {getFirestore}=await import('firebase-admin/firestore')
const {getAuth}=await import('firebase-admin/auth')
const db=getFirestore(),auth=getAuth()
const call=(uid,email,action,data={})=>platformAction.run({auth:{uid,token:{email,email_verified:true}},data:{action,...data}})
test('request approval, admin assignment, publishing, idempotency, and isolation',async()=>{
  await auth.createUser({uid:'super',email:'musthafaak56@gmail.com',emailVerified:true})
  await auth.createUser({uid:'intended-admin',email:'admin@example.com',emailVerified:true})
  await db.doc('platformRoles/super').set({role:'superadmin'})
  const fields={displayName:'Dubai Test Center',type:'center',city:'Dubai',countryCode:'AE',address:'Test address',latitude:25.2,longitude:55.2,timezone:'Asia/Dubai',currency:'AED',locale:'en',description:'',slug:'dubai-test',designatedAdminEmail:'admin@example.com'}
  const {id}=await call('applicant','applicant@example.com','submitApplication',{fields})
  await assert.rejects(()=>call('applicant','applicant@example.com','reviewApplication',{id,status:'approved'}))
  await call('super','musthafaak56@gmail.com','reviewApplication',{id,status:'approved'})
  await call('super','musthafaak56@gmail.com','reviewApplication',{id,status:'approved'})
  assert.equal((await db.doc(`masjids/${id}/members/intended-admin`).get()).data().role,'owner')
  assert.equal((await db.doc(`masjids/${id}/members/applicant`).get()).exists,false)
  const admin=(action,data={})=>call('intended-admin','admin@example.com',action,{centerId:id,...data})
  await admin('settings',{fields,version:1,published:true})
  await assert.rejects(()=>admin('settings',{fields,version:1,published:true}))
  await admin('ledger',{kind:'funds',id:'entry-one',amount:'12.34',note:'private donor note',category:'General'})
  await admin('ledger',{kind:'funds',id:'entry-one',amount:'12.34',note:'private donor note',category:'General'})
  assert.equal((await db.doc(`masjids/${id}/financeState/current`).get()).data().collectedMinor,1234)
  await admin('saveDraft',{kind:'finance',id:'finance',payload:{},version:0})
  await admin('publish',{kind:'finance',id:'finance'})
  const report=(await db.doc(`masjids/${id}/publicFinance/current`).get()).data()
  assert.equal(report.collectedMinor,1234);assert.equal(JSON.stringify(report).includes('private donor'),false)
  await assert.rejects(()=>call('stranger','stranger@example.com','ledger',{centerId:id,kind:'funds',id:'unauthorized',amount:'20'}))
  const prayer={method:'Dubai',offsets:{fajr:5},gaps:{fajr:15}}
  await admin('saveDraft',{kind:'prayer',id:'prayer',payload:prayer,version:0})
  await admin('publish',{kind:'prayer',id:'prayer'})
  assert.equal((await db.doc(`masjids/${id}`).get()).data().prayer.offsets.fajr,5)
  await assert.rejects(()=>admin('saveDraft',{kind:'prayer',id:'prayer',payload:prayer,version:0}))
  const notice={title:'Friday gathering',message:'Welcome',startsAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),surfaces:['home','tv']}
  await admin('saveDraft',{kind:'announcement',id:'notice',payload:notice,version:0})
  assert.equal((await db.doc(`masjids/${id}/announcements/notice`).get()).exists,false)
  await admin('publish',{kind:'announcement',id:'notice'})
  assert.equal((await db.doc(`masjids/${id}/announcements/notice`).get()).data().title,notice.title)
  assert.equal((await db.collection('mailOutbox').get()).size>=3,true)
})
test('invitation requires the intended verified email and cannot be replayed',async()=>{
  await db.doc('masjids/invited').set({status:'draft',displayName:'Invited center'})
  await db.doc('centerInvitations/test-invite').set({centerId:'invited',email:'recipient@example.com',role:'admin',status:'pending',expiresAt:new Date(Date.now()+60000).toISOString()})
  await assert.rejects(()=>call('wrong','wrong@example.com','acceptInvitation',{id:'test-invite'}))
  await call('right','recipient@example.com','acceptInvitation',{id:'test-invite'})
  assert.equal((await db.doc('masjids/invited/members/right').get()).data().role,'admin')
  await assert.rejects(()=>call('right','recipient@example.com','acceptInvitation',{id:'test-invite'}))
})
